[package]
name = "p1689"
version.workspace = true
edition.workspace = true
description = "Borrowed P1689 revision 5 dependency model and JSON parser"
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
memchr.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
