[package]
name = "cpp-deps"
version.workspace = true
edition.workspace = true
description = "Scan, order and compile C++20 named module translation units in Cargo build scripts"
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
cc.workspace = true
p1689.workspace = true
serde_json.workspace = true

[lints]
workspace = true
